version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=danya
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tasks_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
